//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReferEntities : DbContext
    {
        public ReferEntities()
            : base("name=ReferEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<REFERENCIAS> REFERENCIAS { get; set; }
    
        public virtual int PA_INSERTAR_REFERENCIA(string cOD_REFERENCIA, string dES_REFERENCIA, string rEF_CLIENTE, string cODIGO_EAN, string iD_GRUPO, Nullable<int> cNT_ESTANDAR, Nullable<int> pESO, Nullable<bool> oPERATIVA, Nullable<int> lONGITUD_NSERIE, ObjectParameter rETCODE, ObjectParameter mENSAJE)
        {
            var cOD_REFERENCIAParameter = cOD_REFERENCIA != null ?
                new ObjectParameter("COD_REFERENCIA", cOD_REFERENCIA) :
                new ObjectParameter("COD_REFERENCIA", typeof(string));
    
            var dES_REFERENCIAParameter = dES_REFERENCIA != null ?
                new ObjectParameter("DES_REFERENCIA", dES_REFERENCIA) :
                new ObjectParameter("DES_REFERENCIA", typeof(string));
    
            var rEF_CLIENTEParameter = rEF_CLIENTE != null ?
                new ObjectParameter("REF_CLIENTE", rEF_CLIENTE) :
                new ObjectParameter("REF_CLIENTE", typeof(string));
    
            var cODIGO_EANParameter = cODIGO_EAN != null ?
                new ObjectParameter("CODIGO_EAN", cODIGO_EAN) :
                new ObjectParameter("CODIGO_EAN", typeof(string));
    
            var iD_GRUPOParameter = iD_GRUPO != null ?
                new ObjectParameter("ID_GRUPO", iD_GRUPO) :
                new ObjectParameter("ID_GRUPO", typeof(string));
    
            var cNT_ESTANDARParameter = cNT_ESTANDAR.HasValue ?
                new ObjectParameter("CNT_ESTANDAR", cNT_ESTANDAR) :
                new ObjectParameter("CNT_ESTANDAR", typeof(int));
    
            var pESOParameter = pESO.HasValue ?
                new ObjectParameter("PESO", pESO) :
                new ObjectParameter("PESO", typeof(int));
    
            var oPERATIVAParameter = oPERATIVA.HasValue ?
                new ObjectParameter("OPERATIVA", oPERATIVA) :
                new ObjectParameter("OPERATIVA", typeof(bool));
    
            var lONGITUD_NSERIEParameter = lONGITUD_NSERIE.HasValue ?
                new ObjectParameter("LONGITUD_NSERIE", lONGITUD_NSERIE) :
                new ObjectParameter("LONGITUD_NSERIE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_INSERTAR_REFERENCIA", cOD_REFERENCIAParameter, dES_REFERENCIAParameter, rEF_CLIENTEParameter, cODIGO_EANParameter, iD_GRUPOParameter, cNT_ESTANDARParameter, pESOParameter, oPERATIVAParameter, lONGITUD_NSERIEParameter, rETCODE, mENSAJE);
        }
    }
}
